# -*- coding: utf-8 -*-
"""GraphSlim-demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LLG9PYOPnmLCAr0ow0ogRYI8DvLGPk7d

# Code Demo of Using GraphSlim

### Prepare Environment
"""

# ! pip install graphslim==1.1.1
# ! pip install torch_scatter torch_sparse -f https://data.pyg.org/whl/torch-2.3.0+cu121.html

import sys
import torch

from graphslim.config import cli
from graphslim.config import method_config
from graphslim.dataset import get_dataset
from graphslim.evaluation import Evaluator
from graphslim.sparsification import KCenter





"""### Get Config"""

sys.argv = ['']
args = cli(standalone_mode=False)
args.method='kcenter'
args=method_config(args)
args

"""### Get Original Graph"""

graph = get_dataset(args.dataset, args)

"""### Example 1: Reduce Graph using **KCenter** Agent"""

agent = KCenter(setting=args.setting, data=graph, args=args)
reduced_graph = agent.reduce(graph)

"""### Evaluate Reduced Graph (Evaluate 10 Times with different seeds)"""

evaluator = Evaluator(args)
res = evaluator.evaluate(reduced_graph, 'GCN')
print('\nTest Mean Result:', res[0], '+/-', res[1])

"""### Example 2: Reduce Graph using **GCond** Agent"""

sys.argv = ['']
args = cli(standalone_mode=False)
args.method = 'gcond'
args.dataset = 'cora'
args = method_config(args)
args

from graphslim.condensation import GCond
agent = GCond(setting=args.setting, data=graph, args=args)
reduced_graph = agent.reduce(graph)
evaluator = Evaluator(args)
res = evaluator.evaluate(reduced_graph, 'GCN')
print('\nTest Mean Result:', res[0], '+/-', res[1])
